-- Assignment 5-8: Adding Items to a Basket
-- As a shopper selects products on the Brewbean’s site, a procedure is needed to add a newly
-- selected item to the current shopper’s basket. Create a procedure named BASKET_ADD_SP that
-- accepts a product ID, basket ID, price, quantity, size code option (1 or 2), and form code option
-- (3 or 4) and uses this information to add a new item to the BB_BASKETITEM table. The table’s
-- PRIMARY KEY column is generated by BB_IDBASKETITEM_SEQ. Run the procedure with the
-- following values:
-- • Basket ID—14
-- • Product ID—8
-- • Price—10.80
-- • Quantity—1
-- • Size code—2
-- • Form code—4

CREATE OR REPLACE PROCEDURE BASKET_ADD_SP (
  p_basket_id IN NUMBER,
  p_product_id IN NUMBER,
  p_price IN NUMBER,
  p_quantity IN NUMBER,
  p_size_code IN NUMBER,
  p_form_code IN NUMBER
) AS
BEGIN
  INSERT INTO BB_BASKETITEM (
    IDBASKETITEM,
    IDPRODUCT,
    PRICE,
    QUANTITY,
    IDBASKET,
    OPTION1,
    OPTION2
  ) VALUES (
    BB_IDBASKETITEM_SEQ.NEXTVAL,
    p_product_id,
    p_price,
    p_quantity,
    p_basket_id,
    p_size_code,
    p_form_code
  );
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Item added to basket successfully.');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('An error occurred: '
                         || SQLERRM);
END;
/

BEGIN
  BASKET_ADD_SP(14, 8, 10.80, 1, 2, 4);
END;
